title: Srikar Gunisetty
logo: /assets/img/Headshot.jpg

description:
  <p align="center">
  <a href="https://drive.google.com/file/d/1YTFHdcAktD-KIuekF1mmy1Jc4jYJL88d/view?usp=sharing">Resume</a> |
  <a href="https://www.linkedin.com/in/srikargunisetty/">LinkedIn</a> |
  <a href="https://github.com/srikarg1993">GitHub</a>  |
  <a href="https://scholar.google.com/citations?user=u7dj5awAAAAJ&hl=en">Google Scholar</a>
  
theme: jekyll-theme-minimal

# minimal_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# analytics:
#   provider: "google-gtag"
#   google:
#     tracking_id: "UA-224769551-1"
#     anonymize_ip: false # default

#show_downloads: true
# google_analytics: UA-224769551-1
# remote_theme: pages-themes/minimal@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one.
